// ============================================================
// NeuroSustain — Clinical PDF Export
// Generates a professional report for medical review.
// ============================================================

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { get_ratings, get_recent_sessions, get_profile } from '@shared/db.ts';
import { PILLAR_META } from '@shared/constants.ts';
import { format_ms } from '@shared/utils.ts';
import { t } from '@shared/i18n.ts';

/** Generate and download a clinical cognitive report */
export async function export_clinical_report(): Promise<void> {
  const doc = new jsPDF() as any;
  const profile = await get_profile();
  const ratings = await get_ratings();
  const recentSessions = await get_recent_sessions(20);

  const timestamp = new Date().toLocaleString();

  // 1. Header & Branding
  doc.setFillColor(10, 15, 30); // Theme Dark
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('NEUROSUSTAIN', 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('COGNITIVE PERFORMANCE CLINICAL REPORT', 14, 28);
  
  doc.text(`Generated: ${timestamp}`, 196, 28, { align: 'right' });

  // 2. Patient/User Info
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(12);
  doc.text('Patient/User Profile', 14, 50);
  doc.setLineWidth(0.5);
  doc.line(14, 52, 196, 52);

  doc.setFontSize(10);
  doc.text(`User ID: ${profile?.id || 'Local User'}`, 14, 60);
  doc.text(`Total Sessions: ${profile?.totalSessions || 0}`, 14, 66);
  doc.text(`Current Streak: ${profile?.currentStreak || 0} days`, 14, 72);

  // 3. Pillar Ratings Table (Glicko-2)
  doc.setFontSize(12);
  doc.text('Cognitive Pillar Baseline (Glicko-2)', 14, 85);
  
  const ratingData = ratings.map(r => [
    t(PILLAR_META[r.pillar].labelKey),
    Math.round(r.rating).toString(),
    `± ${Math.round(r.rd)}`,
    new Date(r.lastUpdated).toLocaleDateString()
  ]);

  doc.autoTable({
    startY: 88,
    head: [['Pillar', 'Skill Rating', 'Confidence (RD)', 'Last Updated']],
    body: ratingData,
    headStyles: { fillColor: [30, 40, 60] },
    alternateRowStyles: { fillColor: [245, 245, 250] },
  });

  // 4. Recent Session Log
  doc.setFontSize(12);
  doc.text('Recent Session Log', 14, doc.lastAutoTable.finalY + 15);

  const sessionData = recentSessions.map(s => [
    new Date(s.startedAt).toLocaleDateString(),
    s.exerciseType,
    `${Math.round(s.accuracy * 100)}%`,
    format_ms(s.meanReactionTimeMs),
    s.focusScore.toFixed(1),
    `Lv ${Math.round(s.meanDifficulty)}`
  ]);

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 18,
    head: [['Date', 'Exercise', 'Accuracy', 'Avg RT', 'Focus', 'Difficulty']],
    body: sessionData,
    headStyles: { fillColor: [40, 60, 80] },
    styles: { fontSize: 8 },
  });

  // 5. Footer / Disclaimer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'This report is generated by NeuroSustain and is intended for clinical reference. It is not a diagnostic tool.',
      14, 285
    );
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
  }

  doc.save(`NeuroSustain_Report_${new Date().toISOString().slice(0,10)}.pdf`);
}
